-- Dummy data for local `supabase db reset` or paste into the Dashboard SQL Editor (non-prod).
-- Not run by `supabase db push`. Published jobs are visible to the anon key via RLS.

begin;

insert into public.companies (
  id,
  name,
  slug,
  legal_name,
  website_url,
  short_description,
  industry,
  company_size_band,
  is_cdtm_startup,
  hq_city,
  hq_region,
  hq_country
) values
  (
    'a0000000-0000-4000-8000-000000000001'::uuid,
    'CDTM Venture Labs',
    'cdtm-venture-labs',
    'CDTM Venture Labs GmbH',
    'https://cdtm.com',
    'Center for Digital Technology and Management — entrepreneurship and innovation.',
    'education',
    'smb',
    true,
    'Munich',
    'Bavaria',
    'DE'
  ),
  (
    'a0000000-0000-4000-8000-000000000002'::uuid,
    'Alpine Robotics',
    'alpine-robotics',
    null,
    'https://example.com/alpine',
    'Industrial robotics and automation for SMEs.',
    'industrial',
    'startup',
    false,
    'Munich',
    'Bavaria',
    'DE'
  ),
  (
    'a0000000-0000-4000-8000-000000000003'::uuid,
    'North Loop Analytics',
    'north-loop-analytics',
    'North Loop Analytics AG',
    'https://example.com/northloop',
    'Product analytics and experimentation platform.',
    'technology',
    'mid',
    false,
    'Berlin',
    'Berlin',
    'DE'
  );

insert into public.jobs (
  id,
  company_id,
  slug,
  title,
  summary,
  description,
  employment_type,
  work_arrangement,
  location_display,
  city,
  country,
  salary_min,
  salary_max,
  salary_currency,
  salary_period,
  compensation_disclosure,
  experience_level,
  education_level,
  must_have_skills,
  nice_to_have_skills,
  languages,
  application_email,
  valid_through,
  status,
  visa_sponsorship,
  published_at
) values
  (
    'b0000000-0000-4000-8000-000000000001'::uuid,
    'a0000000-0000-4000-8000-000000000001'::uuid,
    'full-stack-engineer-cdtm',
    'Full Stack Engineer (job board)',
    'Ship features for jobs.cdtm.com with FastAPI and Supabase.',
    'You will design and implement APIs, collaborate on domain models, and help ship a public job board used by CDTM students and partners. Stack: Python, FastAPI, PostgreSQL, TypeScript/React (future frontend).',
    'working_student',
    'hybrid',
    'Munich · hybrid',
    'Munich',
    'DE',
    20.00,
    25.00,
    'EUR',
    'hourly',
    'public',
    'entry',
    'Enrolled student or recent graduate in CS or related field.',
    array['python', 'sql', 'git'],
    array['fastapi', 'typescript'],
    array['english'],
    'careers@example.com',
    (current_date + interval '60 days')::date,
    'published',
    false,
    now() - interval '10 days'
  ),
  (
    'b0000000-0000-4000-8000-000000000002'::uuid,
    'a0000000-0000-4000-8000-000000000002'::uuid,
    'robotics-software-engineer',
    'Robotics Software Engineer',
    'C++ and ROS2 for next-gen assembly cells.',
    'Join our core team building motion planning and safety-critical software for industrial robots. You will work closely with hardware and field engineers.',
    'full_time',
    'onsite',
    'Munich · onsite',
    'Munich',
    'DE',
    65000.00,
    85000.00,
    'EUR',
    'yearly',
    'public',
    'mid',
    'BSc/MSc in robotics, CS, or ME.',
    array['c++', 'ros2', 'linux'],
    array['python', 'simulation'],
    array['english', 'german'],
    'jobs@example.com',
    (current_date + interval '45 days')::date,
    'published',
    true,
    now() - interval '3 days'
  ),
  (
    'b0000000-0000-4000-8000-000000000003'::uuid,
    'a0000000-0000-4000-8000-000000000003'::uuid,
    'product-analyst-intern',
    'Product Analyst Intern',
    'Summer internship — metrics, experiments, and dashboards.',
    'Support product managers with SQL analyses, cohort reporting, and experiment readouts. Ideal if you enjoy turning messy data into decisions.',
    'internship',
    'remote',
    'Germany · remote',
    'Berlin',
    'DE',
    null,
    null,
    null,
    null,
    'undisclosed',
    'intern',
    'Ongoing studies in business, economics, or data.',
    array['sql', 'spreadsheets'],
    array['python', 'statistics'],
    array['english'],
    'interns@example.com',
    (current_date + interval '30 days')::date,
    'published',
    false,
    now() - interval '1 day'
  ),
  (
    'b0000000-0000-4000-8000-000000000004'::uuid,
    'a0000000-0000-4000-8000-000000000001'::uuid,
    'devrel-lead-draft',
    'Developer Relations Lead',
    'Draft listing — community, content, and workshops.',
    'This role is not visible to anon readers until published. You would own meetups, documentation, and partner integrations.',
    'full_time',
    'hybrid',
    'Munich',
    'Munich',
    'DE',
    null,
    null,
    null,
    null,
    'confidential',
    'lead',
    null,
    array['public speaking', 'developer tools'],
    array['video'],
    array['english', 'german'],
    null,
    null,
    'draft',
    null,
    null
  );

insert into public.seekers (
  id,
  full_name,
  email,
  headline,
  bio,
  open_to_remote,
  preferred_work_arrangement,
  preferred_locations,
  desired_role_titles,
  skills,
  languages,
  years_of_experience
) values
  (
    'c0000000-0000-4000-8000-000000000001'::uuid,
    'Alex Müller',
    'alex.mueller@example.com',
    'M.Sc. Informatics — backend & distributed systems',
    'CDTM alumnus; interested in early-stage product teams in Munich and Berlin.',
    true,
    'hybrid',
    array['Munich', 'Berlin'],
    array['backend engineer', 'platform engineer'],
    array['python', 'go', 'postgresql', 'kubernetes'],
    array['german', 'english'],
    3
  ),
  (
    'c0000000-0000-4000-8000-000000000002'::uuid,
    'Jordan Kim',
    'jordan.kim@example.com',
    'Product-focused CS student',
    'Seeking working student or internship roles in product analytics.',
    false,
    'onsite',
    array['Munich'],
    array['product analyst', 'data analyst'],
    array['sql', 'python', 'notion'],
    array['english', 'korean'],
    1
  );

commit;
